"""initial schema

Revision ID: 34b6c6d0b4ea
Revises: 
Create Date: 2026-06-27 07:12:00.656801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b6c6d0b4ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(bind, table_name: str) -> bool:
    inspector = sa.inspect(bind)
    return table_name in inspector.get_table_names()


def _index_exists(bind, table_name: str, index_name: str) -> bool:
    inspector = sa.inspect(bind)
    return any(index['name'] == index_name for index in inspector.get_indexes(table_name))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    if not _table_exists(bind, 'users'):
        op.create_table(
            'users',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('email', sa.String(length=255), nullable=False),
            sa.Column('hashed_password', sa.String(length=255), nullable=False),
            sa.Column('full_name', sa.String(length=255), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
    if not _index_exists(bind, 'users', 'ix_users_id'):
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    if not _index_exists(bind, 'users', 'ix_users_email'):
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    if not _table_exists(bind, 'applications'):
        op.create_table(
            'applications',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('job_title', sa.String(length=500), nullable=False),
            sa.Column('company', sa.String(length=500), nullable=False),
            sa.Column('jd_text', sa.Text(), nullable=False),
            sa.Column('original_resume', sa.Text(), nullable=False),
            sa.Column('status', sa.Enum('not_yet', 'applied', 'interviewed', 'rejected', 'offer', name='applicationstatus'), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id']),
            sa.PrimaryKeyConstraint('id')
        )
    if not _index_exists(bind, 'applications', 'ix_applications_id'):
        op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)

    if not _table_exists(bind, 'drafts'):
        op.create_table(
            'drafts',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('application_id', sa.Integer(), nullable=False),
            sa.Column('fit_analysis', sa.Text(), nullable=True),
            sa.Column('resume_rewrite', sa.Text(), nullable=True),
            sa.Column('cover_letter', sa.Text(), nullable=True),
            sa.Column('interview_qa', sa.Text(), nullable=True),
            sa.Column('generated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['application_id'], ['applications.id']),
            sa.PrimaryKeyConstraint('id')
        )
    if not _index_exists(bind, 'drafts', 'ix_drafts_id'):
        op.create_index(op.f('ix_drafts_id'), 'drafts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drafts_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
