"""initial schema

Revision ID: 34b6c6d0b4ea
Revises: 
Create Date: 2026-06-27 07:12:00.656801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b6c6d0b4ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_applications_id', table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_drafts_id', table_name='drafts')
    op.drop_table('drafts')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('drafts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('application_id', sa.INTEGER(), nullable=False),
    sa.Column('fit_analysis', sa.TEXT(), nullable=True),
    sa.Column('resume_rewrite', sa.TEXT(), nullable=True),
    sa.Column('cover_letter', sa.TEXT(), nullable=True),
    sa.Column('interview_qa', sa.TEXT(), nullable=True),
    sa.Column('generated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drafts_id', 'drafts', ['id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=500), nullable=False),
    sa.Column('company', sa.VARCHAR(length=500), nullable=False),
    sa.Column('jd_text', sa.TEXT(), nullable=False),
    sa.Column('original_resume', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=11), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_applications_id', 'applications', ['id'], unique=False)
    # ### end Alembic commands ###
